apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
    spec:
      containers:
        - name: database
          image: bitnami/mongodb:5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: database
              containerPort: 27017
              protocol: TCP
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: database
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: database
