apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.root_pw }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mysql
