apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  helloworld.conf: |
    server {
      listen 80;
      server_name your_domain www.your_domain;

      location / {
          proxy_read_timeout 300s;
          proxy_connect_timeout 75s;
          proxy_pass http://localhost:5000;
      }
    }